### PR TITLE
add downstream integration tests

### PR DESCRIPTION
**Pull request by chriselrod**

### CODE REVIEW

**Comment by Krastanov** [comment]
It seems all the Polyester failures are for cases with `Threads.nthreads() > Sys.CPU_THREADS`.

You probably have already seen this, but just putting it on the record, for me as I am trying to read through and understand this ecosystem and for anyone that might be reading along.

**Comment by chriselrod** [comment]
Are you up for trying to fix it?

The LoopVectorization.jl failure is unrelated.

**Comment by Krastanov** [comment]
Yes, I would be happy to give it a try over the next couple of days. My hope is that it is some silly minor issue with forgetting to take the min of CPU_THREADS and nthreads somewhere.

**Comment by chriselrod** [comment]
> Yes, I would be happy to give it a try over the next couple of days. My hope is that it is some silly minor issue with forgetting to take the min of CPU_THREADS and nthreads somewhere.

I would guess that's the case.

>  for me as I am trying to read through and understand this ecosystem 

And please feel free to ask any questions!

**Pull request merged**
